#
# Manifest for PSGet_Use-Onyphe module
#
# Generated by: MS-LUF
#
# Generated on : 09/02/2020
#

@{

# Module de script ou fichier de module binaire associe e ce manifeste
RootModule = 'use-onyphe.psm1'

# Numero de version de ce module.
ModuleVersion = '1.1'

# editions PS prises en charge
# CompatiblePSEditions = @()

# ID utilise pour identifier de maniere unique ce module
GUID = '85722cd6-f4a3-46b0-9d66-001f818e9a13'

# Auteur de ce module
Author = 'LCU'

# Societe ou fournisseur de ce module
CompanyName = 'lucas-cueff.com'

# Declaration de copyright pour ce module
Copyright = '(c) 2018-2020 lucas-cueff.com Distributed under Artistic Licence 2.0 (https://opensource.org/licenses/artistic-license-2.0).'

# Description de la fonctionnalite fournie par ce module
Description = 'Add few cmdlets to use API from onyphe.io through PowerShell interface'

# Version minimale du moteur Windows PowerShell requise par ce module
PowerShellVersion = '4.0'

# Nom de l'hote Windows PowerShell requis par ce module
# PowerShellHostName = ''

# Version minimale de l'hete Windows PowerShell requise par ce module
# PowerShellHostVersion = ''

# Version minimale du Microsoft .NET Framework requise par ce module. Cette configuration requise est valide uniquement pour PowerShell Desktop Edition.
# DotNetFrameworkVersion = ''

# Version minimale de leenvironnement CLR (Common Language Runtime) requise par ce module. Cette configuration requise est valide uniquement pour PowerShell Desktop Edition.
# CLRVersion = ''

# Architecture de processeur (None, X86, Amd64) requise par ce module
# ProcessorArchitecture = ''

# Modules qui doivent etre importes dans l environnement global prealablement a l importation de ce module
# RequiredModules = @()

# Assemblys qui doivent etre charges prealablement a l importation de ce module
# RequiredAssemblies = @()

# Fichiers de script (.ps1) executes dans l environnement de l appelant prealablement a leimportation de ce module
# ScriptsToProcess = @()

# Fichiers de types (.ps1xml) a charger lors de l importation de ce module
# TypesToProcess = @()

# Fichiers de format (.ps1xml) a charger lors de l importation de ce module
# FormatsToProcess = @()

# Modules a importer en tant que modules imbriques du module specifie dans RootModule/ModuleToProcess
# NestedModules = @()

# Fonctions a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas leentree. Utilisez un tableau vide si vous neavez aucune fonction a exporter.
FunctionsToExport = 'Export-OnypheDataShot', 'Export-OnypheInfo', 'Export-OnypheInfoToFile',
                    'Get-OnypheAlertInfo','Get-OnypheCliFacets','Get-OnypheInfo','Get-OnypheInfoFromCSV','Get-OnypheSearchCategories','Get-OnypheSearchFilters','Get-OnypheSearchFunctions','Get-OnypheSimpleAPIName','Get-OnypheStatsFromObject','Get-OnypheSummary','Get-OnypheSummaryAPIName','Get-OnypheUserInfo','Get-ScriptDirectory',
                    'Import-OnypheEncryptedIKey',
                    'Invoke-APIOnypheAddAlert','Invoke-APIOnypheCtl','Invoke-APIOnypheDataScan','Invoke-APIOnypheDatascanDataMD5','Invoke-APIOnypheDataShot','Invoke-APIOnypheDelAlert','Invoke-APIOnypheExport','Invoke-APIOnypheGeoloc','Invoke-APIOnypheInetnum',
                    'Invoke-APIOnypheListAlert','Invoke-APIOnypheOnionScan','Invoke-APIOnypheOnionShot','Invoke-APIOnyphePastries','Invoke-APIOnypheResolver','Invoke-APIOnypheResolverForward','Invoke-APIOnypheResolverReverse','Invoke-APIOnypheSearch','Invoke-APIOnypheSniffer',
                    'Invoke-APIOnypheSynScan','Invoke-APIOnypheThreatlist','Invoke-APIOnypheTopSite','Invoke-APIOnypheUser','Invoke-APIOnypheVulnscan','Invoke-APISummaryOnypheDomain','Invoke-APISummaryOnypheHostname','Invoke-APISummaryOnypheIP',
                    'Invoke-OnypheAPIV2',
                    'Search-OnypheInfo',
                    'Set-OnypheAlertInfo','Set-OnypheAPIKey','Set-OnypheProxy',
                    'Update-OnypheFacetsFilters'
                    
# Applets de commande a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas l entree. Utilisez un tableau vide si vous neavez aucune applet de commande e exporter.
CmdletsToExport = @()

# Variables a exporter a partir de ce module
# VariablesToExport = @()

# Alias a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas leentree. Utilisez un tableau vide si vous n avez aucun alias a exporter.
AliasesToExport = @('Update-OnypheLocalData','Get-Onyphe', 'Search-Onyphe','Get-OnypheFromCSV','Get-OnypheAlert','Set-OnypheAlert','Export-Onyphe')

# Ressources DSC a exporter depuis ce module
# DscResourcesToExport = @()

# Liste de tous les modules empaquetes avec ce module
# ModuleList = @()

# Liste de tous les fichiers empaquetes avec ce module
FileList = 'use-onyphe.psm1'

# Donnees privees a transmettre au module specifie dans RootModule/ModuleToProcess. Cela peut egalement inclure une table de hachage PSData avec des metadonnees de modules supplementaires utilisees par PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('API','onyphe.io','onyphe','shodan','search','engine')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MS-LUF/Use-Onyphe'

        # A URL to an icon representing this module.
        IconUri = 'https://www.onyphe.io/img/logo-solo.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'v1.1 : add new APIv2, migrate from APIv1 to full APIv2 (except bulk API that will be provided in 1.2);remove temporary fix for empty array in APIv2;update deserialization of psobject'
        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# URI HelpInfo de ce module
# HelpInfoURI = ''

# Le prefixe par defaut des commandes a ete exporte a partir de ce module. Remplacez le prefixe par defaut a l aide de Import-Module -Prefix.
# DefaultCommandPrefix = ''

}