#
# Manifest for Use-Onyphe module
#
# Generated by: lucas-cueff.com
#
# Generated on : 20/11/2021
#

@{

# Module de script ou fichier de module binaire associe e ce manifeste
RootModule = 'use-onyphe.psm1'

# Numero de version de ce module.
ModuleVersion = '2.2.2'

# editions PS prises en charge
# CompatiblePSEditions = @()

# ID utilise pour identifier de maniere unique ce module
GUID = '85722cd6-f4a3-46b0-9d66-001f818e9a13'

# Auteur de ce module
Author = 'MS-LUF'

# Societe ou fournisseur de ce module
CompanyName = 'lucas-cueff.com'

# Declaration de copyright pour ce module
Copyright = '(c) 2018-2021 lucas-cueff.com Distributed under Artistic Licence 2.0 (https://opensource.org/licenses/artistic-license-2.0).'

# Description de la fonctionnalite fournie par ce module
Description = 'Add few cmdlets to use API from onyphe.io through PowerShell interface'

# Version minimale du moteur Windows PowerShell requise par ce module
PowerShellVersion = '4.0'

# Nom de l'hote Windows PowerShell requis par ce module
# PowerShellHostName = ''

# Version minimale de l'hete Windows PowerShell requise par ce module
# PowerShellHostVersion = ''

# Version minimale du Microsoft .NET Framework requise par ce module. Cette configuration requise est valide uniquement pour PowerShell Desktop Edition.
# DotNetFrameworkVersion = ''

# Version minimale de leenvironnement CLR (Common Language Runtime) requise par ce module. Cette configuration requise est valide uniquement pour PowerShell Desktop Edition.
# CLRVersion = ''

# Architecture de processeur (None, X86, Amd64) requise par ce module
# ProcessorArchitecture = ''

# Modules qui doivent etre importes dans l environnement global prealablement a l importation de ce module
# RequiredModules = @()

# Assemblys qui doivent etre charges prealablement a l importation de ce module
# RequiredAssemblies = @()

# Fichiers de script (.ps1) executes dans l environnement de l appelant prealablement a leimportation de ce module
# ScriptsToProcess = @()

# Fichiers de types (.ps1xml) a charger lors de l importation de ce module
# TypesToProcess = @()

# Fichiers de format (.ps1xml) a charger lors de l importation de ce module
# FormatsToProcess = @()

# Modules a importer en tant que modules imbriques du module specifie dans RootModule/ModuleToProcess
# NestedModules = @()

# Fonctions a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas leentree. Utilisez un tableau vide si vous neavez aucune fonction a exporter.
FunctionsToExport = 'Export-OnypheBulkInfo','Export-OnypheBulkSummaryInfo','Export-OnypheDataShot','Export-OnypheDiscoveryInfo','Export-OnypheInfo','Export-OnypheInfoToFile','Get-OnypheAlertInfo','Get-OnypheASDAPIName','Get-OnypheASDInfo','Get-OnypheCliFacets','Get-OnypheDiscoveryCategories','Get-OnypheInfo','Get-OnypheInfoFromCSV','Get-OnypheSearchCategories','Get-OnypheSearchFilters','Get-OnypheSearchFunctions','Get-OnypheSimpleAPIName','Get-OnypheBulkCategories','Get-OnypheBulkAPIType','Get-OnypheStatsFromObject','Get-OnypheSummary','Get-OnypheSummaryAPIName','Get-OnypheUserInfo','Import-OnypheEncryptedIKey','Search-OnypheInfo','Set-OnypheAlertInfo','Set-OnypheAPIKey','Set-OnypheProxy','Update-OnypheFacetsFilters', 'Get-OnypheSimpleBestAPIName'
                    
# Applets de commande a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas l entree. Utilisez un tableau vide si vous neavez aucune applet de commande e exporter.
CmdletsToExport = @()

# Variables a exporter a partir de ce module
# VariablesToExport = @()

# Alias a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas leentree. Utilisez un tableau vide si vous n avez aucun alias a exporter.
AliasesToExport = @('Export-Onyphe','Get-Onyphe','Get-OnypheAlert','Get-OnypheFromCSV','Search-Onyphe','Set-OnypheAlert','Update-OnypheLocalData','Export-OnypheBulkSimple','Export-OnypheBulkSummary','Export-OnypheBulkDiscovery')

# Ressources DSC a exporter depuis ce module
# DscResourcesToExport = @()

# Liste de tous les modules empaquetes avec ce module
# ModuleList = @()

# Liste de tous les fichiers empaquetes avec ce module
FileList = 'use-onyphe.psm1'

# Donnees privees a transmettre au module specifie dans RootModule/ModuleToProcess. Cela peut egalement inclure une table de hachage PSData avec des metadonnees de modules supplementaires utilisees par PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('API','onyphe.io','onyphe','shodan','search','engine')

        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/artistic-license-2.0'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MS-LUF/Use-Onyphe'

        # A URL to an icon representing this module.
        IconUri = 'https://www.onyphe.io/img/logo-solo.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'v2.2.2 : documentation-only release - live-confirmed (8.8.8.8, 1.1.1.1) that the Summary API (v2/summary/<type>/<value>, wrapped by Get-OnypheSummary) does not paginate either, same as the Simple API caveat documented in v2.2.1: any -Page value returns the same first page of results, with no error or warning, and the server always reports page:1 back regardless of what was requested. No code/behavior change - Get-OnypheSummary.ps1 and the three Invoke-APISummaryOnyphe<IP,Domain,Hostname> private wrappers'' -Page doc blocks, Howto.md, docs/Get-OnypheSummary.md and en-US/use-onyphe-help.xml now carry a NOTE pointing to Search-OnypheInfo/Export-OnypheInfo for anyone who needs more than one page of results. v2.2.1 : fixes Export-OnypheDiscoveryInfo (and every Invoke-APIBulkDiscoveryOnyphe<Category> private wrapper) silently capping each OQL query line in the Discovery API at 100 results, even when far more results actually match - Onyphe truncates without any error/warning unless a size query-string parameter is supplied. Adds an optional -Size <1-10000> parameter, opt-in, default behavior unchanged (still 100 when omitted) to avoid a breaking change. Live-verified: the same query returned 100 results by default and 2791 with -Size 10000, matching the account holder''s own count from the Onyphe website (2789, small drift from new data indexed between checks). No breaking changes since v2.2.0. v2.2.0 : adds Get-OnypheASDInfo/Get-OnypheASDAPIName, wrapping the 9 licensed "standard" ASD (Attack Surface Discovery) APIv1 endpoints (domaintld, domainwildcard, domaincertso, certsodomain, certsowildcard, dnsdomainns, dnsdomainmx, dnsdomainsoa, dnsdomainexist) - BETA endpoints requiring a Griffin View/ASM Edition non-commercial licence. The advanced Pivot Query ASD API is not yet implemented (not licensed on the account used for verification, deferred until it can be live-tested). See README.md for the full list.'
        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# URI HelpInfo de ce module
# HelpInfoURI = ''

# Le prefixe par defaut des commandes a ete exporte a partir de ce module. Remplacez le prefixe par defaut a l aide de Import-Module -Prefix.
# DefaultCommandPrefix = ''

}